# Generated by Django 3.0.3 on 2020-02-22 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blogger.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blogger.Post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blogger.User')),
            ],
        ),
    ]
